---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: demo-concourse-flux
  name: helloworld
  labels:
    app: helloworld
spec:
  strategy:
      canary:
        analysis:
          templates:
          - templateName: webcheck
        args:
        - name host
          value: colorapi
        steps:
        - setWeight: 20
        - pause:
            duration: "30s"
        - setWeight: 50
        - pause:
            duration: "30s"  
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      namespace: demo-concourse-flux
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: particule/demo-concourse-flux:1.0.7
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-concourse-flux
  name: helloworld-svc
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
  - name: host
  metrics:
  - name: webcheck
    failureLimit: 1
    interval: 5
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.host}}/"
        jsonPath: "{$.status}"
